/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    InvoiceProgress: typeof import('./src/components/dashboard/InvoiceProgress.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    ListViewBuilder: typeof import('./src/components/ListViewBuilder.vue')['default']
    MobileLayout: typeof import('./src/components/Layouts/MobileLayout.vue')['default']
    RecentInvoices: typeof import('./src/components/dashboard/RecentInvoices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
